Prova1Bim/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Prova1Bim.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Cadastro()
        {
            return View();
        }
        public ActionResult Encaminhar(Models.Cliente cli)
        {
            if(!string.IsNullOrEmpty("Gravar"))
            {
                if (cli.Gravar(cli))
                {
                    ViewBag.Msg = "Gravado com sucesso !!";
                }
                return View("Cadastro");
            }
            else
            {
                return View("Cancelar");
            }
        }
        public ActionResult Gravar(Models.Cliente cli)
        {
            if (ModelState.IsValid)
            {
                if (cli.Gravar(cli))
                {
                    ViewBag.Msg = "Gravado com sucesso !!";
                }
                return View("Cadastro");
            }
            else
            {
                ViewBag.Msg = "Erro ao gravar";
                return View("Cadastro");
            }
        }
        public ActionResult Cancelar(Models.Cliente cli)
        {
            return View("Cadastro");
        }
    }
}

Prova1Bim/Controllers/PesquisaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Prova1Bim.Controllers
{
    public class PesquisaController : Controller
    {
        // GET: Pesquisa
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Pesquisar()
        {
            return View();
        }
    }
}

Prova1Bim/Controllers/TelefoneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Prova1Bim.Controllers
{
    public class TelefoneController : Controller
    {
        // GET: Telefone
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Cadastro()
        {
            return View();
        }
    }
}

Prova1Bim/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Estilos.css" rel="stylesheet" />
    <script src="~/Scripts/script.js"></script>
    <title>Prova 1° Bimestre</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li>@Html.ActionLink("Cadastrar Contato","Cadastro", "Cliente")</li>
                <li>@Html.ActionLink("Cadastro Telefone", "Cadastro", "Telefone")</li>
                <li>@Html.ActionLink("Pesquisar Contato", "Pesquisar", "Pesquisa")</li>
            </ul>
        </nav>
        <div class="info">
            <p>Nome: Ederson de Abreu Neves</p><br />
            <p>RA: 3391305703</p>
        </div>
       
    </header>
    <div class="corpo"> 
        @RenderBody()
    </div>
    <footer>
        <p>Prova do 1° Bimestre</p>
    </footer>
</body>
</html>